[global]
   workgroup = LXCFH
   server string = LXC File Hub Samba
   security = user
   map to guest = Bad User
   passdb backend = tdbsam
   load printers = no
   printing = bsd
   disable spoolss = yes
   server min protocol = SMB2
   client min protocol = SMB2
   fruit:metadata = stream
   fruit:model = MacSamba
   vfs objects = fruit streams_xattr
   log file = /var/log/samba/log.%m
   max log size = 50
   pid directory = /run/samba

[lxcfh]
   comment = LXC File Hub shared storage
   path = /fuse-share
   browseable = yes
   read only = no
   guest ok = no
   valid users = lxcfh
   create mask = 0664
   directory mask = 0775
   force user = lxcfh
   force group = lxcfh
